import Head from 'next/head'
import Image from 'next/image'
import CurrentDevice from './current-device'
import Folders from './folders'
import Remotes from './remotes'
function Card({ title, children, ...rest }) {
    return <article className="card--root" {...rest}>
        <h3 className="card--title">{title}</h3>
        <div className="card--contents">{children}</div>

    </article>
}
export default function Home() {
    return (
        <main className="mainPage--root">
            <Head>
                <title>Offline Sync</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Card title="Folders" style={{gridRow:'2 span'}} >
                <Folders />
            </Card>
            <Card title="This Device">
            <CurrentDevice />
            </Card>
            <Card title="Remotes">
            <Remotes />
                
            </Card>
        </main>
    )
}
